### ISSUE TITLE
Malimbe.XmlDocumentationAttribute problem in Unity

### ISSUE THREAD

**Issue by castana1962** [ExtendRealityLtd/VRTK.Prefabs#41]
Hi
I am making a Unity project (2018.4.20f1 LTS version) and  VTRK
According to the VRTK Prefabs documentation, I added this code to the manifest.json file
At the top......

"scopedRegistries": [
    {
      "name": "npmjs",
      "url": "https://registry.npmjs.org/",
      "scopes": [
        "io.extendreality"
      ]
    }
  ],

and the dependencies part the following code

 "io.extendreality.vrtk.prefabs": "1.1.11"

After that, the Unity updated the VRTK Prefabs files succesfully.

But when I built and ran the project , I am having an error. This is the following

Malimbe.XmlDocumentationAttribute: The field 'VRTK.Prefabs.Interactions.InteractorVisibilityModifier.InteractorVisibilityModifierFacade/UnityEvent VRTK.Prefabs.Interactions.InteractorVisibilityModifier.InteractorVisibilityModifierFacade::Shown' is annotated to be documented by XML documentation comments but none were found.

For it, Could you help me with it?
Thanks for your time
Alejandro

**Comment by thestonefox** [comment]
You can ignore that message, it won't actually break your code from compiling.

although I'm not entirely sure why you're getting that error because looking at the line of code at:

https://github.com/ExtendRealityLtd/VRTK.Prefabs/blob/master/Interactions/InteractorVisibilityModifier/SharedResources/Scripts/InteractorVisibilityModifierFacade.cs#L26-L30

There is a xml documentation for that event.

**Comment by castana1962** [comment]
Hi thestonefox
First, thanks for your help
On the other hand I am trying to build and run the Unity project to Oculus Quest and I cannot do it because, I have the error mentioned above.
Best Regards
Alejandro

**Comment by thestonefox** [comment]
I've just created a fresh project in 2018.4.21f1

imported VRTK.Prefabs 1.1.11 (from copying and pasting above)

And I'm not getting the error you are reporting.

Could you try in a fresh project to ensure it works for you also?

**Comment by bddckr** [comment]
As mentioned in https://github.com/ExtendRealityLtd/Malimbe/issues/61 it looks like you're using a wrong version of the package or something.
